[build]
command = "npm run build --prefix client"
publish = "client/build"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200